import Head from 'next/head'

import { useRouter } from 'next/router'

export default function Article({person}) {
  const router = useRouter()
  const {id} = router.query
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="">
        {id}
      </p>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('https://swapi.dev/api/people/')
  const person = await res.json()
  return {
    props: {
      person
    }
  }
}
